# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42255652617ac98f7059fc0d3f1ee2f70e6cf9d3858ab74a4b8b2be6a5af7136a625344de95a702c547e65f60c39efb05827479f87e3cfa7963b31c1d56914d8

test:
  secret_key_base: 088069fb312fd23238ef234e648f3718d4858d07a3fe79c9e2229430dc9e3f33eba69287b2c0b2a599c292cad6297a30e58d741a8132c2d7c65006323a83facc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
